name: ğŸ§ª Backend CI

on:
  push:
    paths:
      - 'back/***'
  pull_request:
    paths:
      - 'back/**'

defaults:
  run:
    working-directory: back

jobs:
  backend-checks:
    name: âš™ï¸ Backend Python Checks
    runs-on: ubuntu-latest

    steps:
      - name: â¬‡ï¸ Checkout repo
        uses: actions/checkout@v3

      - name: âš™ï¸ Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  # ou 3.10, conforme sua stack

      - name: ğŸ“¦ Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: ğŸ“¦ Install Dependencies
        run: poetry install

      - name: ğŸ§¼ Run Black
        run: poetry run black . --check

      - name: ğŸ” Run Flake8
        run: poetry run flake8 src

      - name: ğŸ“¥ Run isort
        run: poetry run isort . --check-only

